### PR TITLE
Bump the tweeny submodule version to master, now the demos build for me

### LINKED ISSUE #1: Couldn't build with g++ 8.3.0 or clang 7.0.1-8
Hello, this looks like a fun library, and I thought I'd try building the demos to take a look.

Unfortunately it failed to build for me, complaining about some new C++ features that I'm not very familiar with... but g++ 8 certainly supports `-std=c++11` which is what I found in `CMakeLists.txt` of both `tweeny` and `tweeny-demos`.

Forgive me if I'm doing something obviously wrong, C++ is not something I do every day.

I tried it with `clang 7.0.1-8` as well and got a similar complaint about the `default = defaultEasing{}` after the struct definition.

```
cpp --version
cpp (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```make easings
[ 50%] Building CXX object src/CMakeFiles/easings.dir/easings/easings.cpp.o
In file included from /home/blake/Downloads/tweeny-demos/libs/tweeny/include/tweenpoint.tcc:37,
                 from /home/blake/Downloads/tweeny-demos/libs/tweeny/include/tweenpoint.h:80,
                 from /home/blake/Downloads/tweeny-demos/libs/tweeny/include/tween.h:38,
                 from /home/blake/Downloads/tweeny-demos/libs/tweeny/include/tweeny.h:81,
                 from /home/blake/Downloads/tweeny-demos/src/easings/easings.cpp:30:
/home/blake/Downloads/tweeny-demos/libs/tweeny/include/easing.h:178:14: error: expected ‘;’ after struct definition
             } default = defaultEasing{};
              ^
              ;
/home/blake/Downloads/tweeny-demos/libs/tweeny/include/easing.h:147:13: error: a storage class can only be specified for objects and functions
             static constexpr struct defaultEasing {
             ^~~~~~
/home/blake/Downloads/tweeny-demos/libs/tweeny/include/easing.h:178:15: error: expected unqualified-id before ‘default’
             } default = defaultEasing{};
               ^~~~~~~
In file included from /home/blake/Downloads/tweeny-demos/libs/tweeny/include/tweenpoint.tcc:38,
                 from /home/blake/Downloads/tweeny-demos/libs/tweeny/include/tweenpoint.h:80,
                 from /home/blake/Downloads/tweeny-demos/libs/tweeny/include/tween.h:38,
                 from /home/blake/Downloads/tweeny-demos/libs/tweeny/include/tweeny.h:81,
                 from /home/blake/Downloads/tweeny-demos/src/easings/easings.cpp:30:
/home/blake/Downloads/tweeny-demos/libs/tweeny/include/easingresolve.h: In static member function ‘static void tweeny::detail::easingresolve<I, TypeTuple, FunctionTuple, tweeny::easing::defaultEasing, Fs ...>::impl(FunctionTuple&, tweeny::easing::defaultEasing, Fs ...)’:
/home/blake/Downloads/tweeny-demos/libs/tweeny/include/easingresolve.h:81:37: error: expected unqualified-id before ‘default’
                 get<I>(b) = easing::default.run<ArgType>;
                                     ^~~~~~~
/home/blake/Downloads/tweeny-demos/libs/tweeny/include/easingresolve.h:81:35: error: expected ‘;’ before ‘default’
                 get<I>(b) = easing::default.run<ArgType>;
                                   ^ ~~~~~~~
                                   ;
In file included from /home/blake/Downloads/tweeny-demos/libs/tweeny/include/tweenpoint.h:80,
                 from /home/blake/Downloads/tweeny-demos/libs/tweeny/include/tween.h:38,
                 from /home/blake/Downloads/tweeny-demos/libs/tweeny/include/tweeny.h:81,
                 from /home/blake/Downloads/tweeny-demos/src/easings/easings.cpp:30:
/home/blake/Downloads/tweeny-demos/libs/tweeny/include/tweenpoint.tcc: In constructor ‘tweeny::detail::tweenpoint<Ts>::tweenpoint(Ts ...)’:
/home/blake/Downloads/tweeny-demos/libs/tweeny/include/tweenpoint.tcc:72:25: error: expected unqualified-id before ‘default’
             via(easing::default);
                         ^~~~~~~
make[3]: *** [src/CMakeFiles/easings.dir/build.make:63: src/CMakeFiles/easings.dir/easings/easings.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:145: src/CMakeFiles/easings.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:157: src/CMakeFiles/easings.dir/rule] Error 2
make: *** [Makefile:199: easings] Error 2
```

### PR DESCRIPTION
**Pull request by blak3mill3r**
Fixes #1

### CODE REVIEW

**Comment by blak3mill3r** [comment]
Thanks for this library, btw, it looks great!

**Comment by mobius3** [comment]
Mergin. Thank you very much!
